music/urls.py
from django.urls import path
from . import views #look for views.py in the same directory

app_name = 'music' #namespacing urls 

urlpatterns = [
    #/music/
    path('', views.IndexView.as_view(), name='index'), #index is the home page of the section in views.py
    #/music/<album_id>/
    path('<pk>/', views.DetailView.as_view(), name='detail'), #name is used to remove hardcoded urls
]

todo/urls.py
from django.urls import path
from . import views #look for views.py in the same directory

app_name = 'todo' #namespacing urls 

urlpatterns = [
    #/todo/
    path('', views.index, name='index'), #index is the home page of the section in views.py
]

website/urls.py
#first page which server looks for
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls')), #this is gonna include our apps urls to main 
    path('todo/', include('todo.urls')),
]

music/models.py
#each variable in the class is converted to a column in the table in db
from django.db import models

class Album(models.Model):
    #variable name is same name as col name in table
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def __str__(self): #string repr of this object
        return self.album_title + ' - ' + self.artist

class Song(models.Model): #we need our song to be a part of any album
    #we need to link these two classes together
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self): #string repr of this object
        return self.song_title

todo/models.py
from django.db import models

class Task(models.Model):
    title = models.CharField(max_length=250)
    complete = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __srt__(self):
        return self.title

music/views.py
from django.views import generic
from .models import Album

class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums' #to change the default name which is object_list

    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'

    

todo/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    return render(request, "todo/index.html")

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}My Website{% endblock %}</title>
        {% load staticfiles %}

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Satisfy" rel='stylesheet' type="text/css">
        <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    </head>
    <body>
        <div class="container">
            <!--header-->
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
              
                <!--items-->
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                      <a class="nav-link" href="#">Albums</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link fas fa-music" href="#">Songs</a>
                    </li>
                    <li class="nav-item">
                      <form class="form-inline my-2 my-lg-0 navbar-left" method="GET" action="#" role="search">
                        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
                      </form>
                    </li>
                  </ul>
                </div>
                
                <div class="collapse navbar-collapse ">
                  <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                      <a class="nav-link" href="#">Add Album</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">Logout</a>
                    </li>
                  </ul>
                </div>
            </nav>
          </div>
          {% block body %}
          {% endblock %}
    </body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}Album Details{% endblock %}

{% block body %} <br>
<div class="container">
    <img src="{{ album.album_logo }}">

    <h1>{{ album.album_title }}</h1>
    <h3>{{ album.artist }}</h3>

    {% for song in album.song_set.all %}
        {{ song.song_title }}
        {% if song.is_favorite %}
            <img src="https://i.imgur.com/b9b13Rd.png" />
        {% endif %}<br>
    {% endfor%}
</div>
{% endblock %}

music/templates/music/index.html
{% extends 'music/base.html' %}

{% block body %}
<br>
<div class="container">
  <ul>
      {% for album in all_albums %}
      <li><a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a></li>
      {% endfor %}
  </ul>
</div>
{% endblock %}

todo/templates/todo/index.html
<h2>My todo app</h2>